apiVersion: apps/v1
kind: Deployment
metadata:
  name: employeek8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: employeek8s
          image: mkevin01/employeek8s:latest
          ports:
            - containerPort: 8082