version: '3.8'
services:
  employ-management-app:
    build:
      context: .
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/employManagement
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      - db
    networks:
      - employ-management-network

  db:
    image: postgres
    environment:
      POSTGRES_DB: employManagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    networks:
      - employ-management-network

networks:
  employ-management-network:
    driver: bridge
